# .readthedocs.yml
# Read the Docs configuration file
version: 2

# Sphinx config
sphinx:
  builder: html
  configuration: docs/source/conf.py

# Python config
build:
  image: latest
python:
  version: 3.6
  system_packages: true
conda:
  environment: docs/source/environment.yml
