# Travis Continuos Integration
# Currently only tests notebook files
# Based on http://conda.pydata.org/docs/travis.html
sudo: false # use container based build
language: python
notifications:
    email: false

python:
  - "3.6"

install:
  - which pip
  - which python
  - pip install -r docs/requirements.txt

script:
  - pushd docs
  - make html
  - popd

