# Hard requirements for notebook examples and documentation build
# WARNING: Keep this up-to-date with ci/environment.yml
# * basemap is broken as of matplotlib >= 3.3 so for documentation
#   use 3.2.1. Probably lots of basemap holdouts for next ~5 years.
# * basemap geography is weird with the geos >= 3.9.0 required by cartopy >=
#   0.19, but important to use 0.19 becuase it fixes padding, so live with it.
# * cartopy 0.20 makes grid labels look nicer, but it requires python 3.9.
#   will wait a couple years to catch up to them and keep python 3.6 for now.
# * pyqt5 is needed by pyplot, RTD server *happens* to already have it
#   but creating local environment will fail.
# * jinja >= 3.0 and nbsphinx >= 0.8.2 seem to break default ReST roles when
#   jupytext notebooks are converted to HTML. Interpreted as italics instead.
# * docutils >= 0.17 breaks bullet points. See the following thread
#   for more info: https://github.com/readthedocs/sphinx_rtd_theme/issues/1115
name: proplot-dev
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - pandas
  - xarray
  - matplotlib==3.2.1
  - cartopy==0.19.0.post1
  - shapely==1.7.1
  - ipykernel
  - pandoc
  - pip
  - pip:
    - ..
    - pyqt5
    - docutils==0.16
    - sphinx>=3.0
    - sphinx-copybutton
    - sphinx_rtd_theme==0.4.3
    - jinja2==2.11.3
    - nbsphinx==0.8.1
    - jupytext
    - git+https://github.com/lukelbd/sphinx-automodapi@proplot-mods
